/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cw721Poap.types";
import * as _1 from "./Cw721Poap.client";
import * as _2 from "./Cw721Remarkables.types";
import * as _3 from "./Cw721Remarkables.client";
import * as _4 from "./Poap.types";
import * as _5 from "./Poap.client";
import * as _6 from "./PoapManager.types";
import * as _7 from "./PoapManager.client";
import * as _8 from "./Remarkables.types";
import * as _9 from "./Remarkables.client";
import * as _10 from "./Tips.types";
import * as _11 from "./Tips.client";
import * as _12 from "./Cw721Base.types";
import * as _13 from "./Cw721Base.client";
export namespace contracts {
  export const Cw721Poap = { ..._0,
    ..._1
  };
  export const Cw721Remarkables = { ..._2,
    ..._3
  };
  export const Poap = { ..._4,
    ..._5
  };
  export const PoapManager = { ..._6,
    ..._7
  };
  export const Remarkables = { ..._8,
    ..._9
  };
  export const Tips = { ..._10,
    ..._11
  };
  export const Cw721Base = { ..._12,
    ..._13
  };
}