/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ServiceFee = {
  fixed: {
    amount: Coin[];
  };
} | {
  percentage: {
    value: Decimal;
  };
};
export type Uint128 = string;
export type Decimal = string;
export type Uint64 = string;
export interface InstantiateMsg {
  admin: string;
  service_fee?: ServiceFee | null;
  subspace_id: Uint64;
  tips_history_size: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  send_tip: {
    amount: Coin[];
    target: Target;
  };
} | {
  update_service_fee: {
    new_fee?: ServiceFee | null;
  };
} | {
  update_admin: {
    new_admin: string;
  };
} | {
  update_saved_tips_history_size: {
    new_size: number;
  };
} | {
  claim_fees: {
    receiver: string;
  };
};
export type Target = {
  content_target: {
    post_id: Uint64;
  };
} | {
  user_target: {
    receiver: string;
  };
};
export type QueryMsg = {
  config: {};
} | {
  user_received_tips: {
    user: string;
  };
} | {
  user_sent_tips: {
    user: string;
  };
} | {
  post_received_tips: {
    post_id: Uint64;
  };
};
export type Addr = string;
export interface QueryConfigResponse {
  admin: Addr;
  service_fee?: ServiceFee | null;
  subspace_id: Uint64;
  tips_history_size: number;
}
export interface TipsResponse {
  tips: Tip[];
}
export interface Tip {
  amount: Coin[];
  block_height: Uint64;
  post_id?: Uint64 | null;
  receiver: Addr;
  sender: Addr;
}